#spring:
#  cassandra:
#      schema-action: CREATE_IF_NOT_EXISTS

  #jackson:
  #  serialization:
  #    WRITE_DATES_AS_TIMESTAMPS: false

#  jackson:
#    date-format: yyyy-MM-dd,MM-dd-yyyy

astra:
  api:
    application-token: ${APP_TOKEN}
    #database-id: 5f14dfb6-a684-4460-9c7b-36cfa78e78f0
    database-id: ${DATABASE_ID}
    database-region: ${DATABASE_REGION}
    cross-region-failback: false
    grpc:
      enabled: true
